import {
  Archive,
  BadgeCheck,
  Crop,
  Edit3,
  FileImage,
  FileInput,
  FileOutput,
  FileText,
  Files,
  FormInput,
  ImagePlus,
  Lock,
  Merge,
  RotateCw,
  Scissors,
  Shield,
  Signature,
  Sparkles,
  Stamp,
  Trash2,
  Unlock,
  WandSparkles,
} from "lucide-react";

export type ToolCategory = "Organize PDF" | "Optimize PDF" | "Edit PDF" | "Convert" | "Security" | "Other Tools";

export type ToolDefinition = {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  accepts: string;
  multiple: boolean;
  icon: typeof Files;
  options: Record<string, string | number | boolean>;
};

export const toolCategories: ToolCategory[] = [
  "Organize PDF",
  "Optimize PDF",
  "Edit PDF",
  "Convert",
  "Security",
  "Other Tools",
];

export const tools: ToolDefinition[] = [
  {
    id: "merge",
    name: "Merge PDF",
    description: "Combine PDFs in upload order.",
    category: "Organize PDF",
    accepts: "application/pdf",
    multiple: true,
    icon: Merge,
    options: {},
  },
  {
    id: "split",
    name: "Split PDF",
    description: "Split by ranges, pages, or every N pages.",
    category: "Organize PDF",
    accepts: "application/pdf",
    multiple: false,
    icon: Scissors,
    options: { mode: "ranges", ranges: "1-3,4-6", every: 1 },
  },
  {
    id: "delete-pages",
    name: "Delete Pages",
    description: "Remove selected pages.",
    category: "Organize PDF",
    accepts: "application/pdf",
    multiple: false,
    icon: Trash2,
    options: { pages: "1" },
  },
  {
    id: "organize-pages",
    name: "Organize Pages",
    description: "Reorder, rotate, and keep selected pages.",
    category: "Organize PDF",
    accepts: "application/pdf",
    multiple: false,
    icon: RotateCw,
    options: { order: "", rotate: 0 },
  },
  {
    id: "compress",
    name: "Compress PDF",
    description: "Reduce file size with Ghostscript presets.",
    category: "Optimize PDF",
    accepts: "application/pdf",
    multiple: false,
    icon: Archive,
    options: { quality: "recommended" },
  },
  {
    id: "page-numbers",
    name: "Page Numbers",
    description: "Add or remove page numbers.",
    category: "Optimize PDF",
    accepts: "application/pdf",
    multiple: false,
    icon: BadgeCheck,
    options: { action: "add", position: "bottom-center", format: "Page {n}", color: "#111827", size: 11 },
  },
  {
    id: "edit",
    name: "Edit PDF",
    description: "Add text, boxes, drawing marks, images, redactions, and crops.",
    category: "Edit PDF",
    accepts: "application/pdf,image/png,image/jpeg",
    multiple: true,
    icon: Edit3,
    options: { text: "PDFForge", page: 1, x: 72, y: 72, redact: false, redactTerms: "", crop: false },
  },
  {
    id: "crop",
    name: "Crop PDF",
    description: "Apply page crop margins.",
    category: "Edit PDF",
    accepts: "application/pdf",
    multiple: false,
    icon: Crop,
    options: { top: 24, right: 24, bottom: 24, left: 24 },
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert with LibreOffice/Poppler pipeline in Docker.",
    category: "Convert",
    accepts: "application/pdf",
    multiple: false,
    icon: FileOutput,
    options: {},
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract tabular text to spreadsheet-friendly CSV/XLSX.",
    category: "Convert",
    accepts: "application/pdf",
    multiple: false,
    icon: FileOutput,
    options: {},
  },
  {
    id: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    description: "Convert PDF pages to slide deck assets.",
    category: "Convert",
    accepts: "application/pdf",
    multiple: false,
    icon: FileOutput,
    options: {},
  },
  {
    id: "office-to-pdf",
    name: "Office to PDF",
    description: "Word, Excel, and PowerPoint to PDF using LibreOffice.",
    category: "Convert",
    accepts: ".doc,.docx,.xls,.xlsx,.ppt,.pptx",
    multiple: false,
    icon: FileInput,
    options: {},
  },
  {
    id: "pdf-to-image",
    name: "PDF to JPG/PNG",
    description: "Render individual pages or a ZIP of all pages.",
    category: "Convert",
    accepts: "application/pdf",
    multiple: false,
    icon: FileImage,
    options: { format: "png", pages: "all" },
  },
  {
    id: "image-to-pdf",
    name: "JPG/PNG to PDF",
    description: "Create a PDF from images.",
    category: "Convert",
    accepts: "image/png,image/jpeg",
    multiple: true,
    icon: ImagePlus,
    options: {},
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    description: "Render uploaded HTML into PDF.",
    category: "Convert",
    accepts: ".html,text/html",
    multiple: false,
    icon: FileText,
    options: {},
  },
  {
    id: "protect",
    name: "Protect PDF",
    description: "Encrypt with password and permissions.",
    category: "Security",
    accepts: "application/pdf",
    multiple: false,
    icon: Lock,
    options: { password: "", allowPrinting: true, allowCopying: false },
  },
  {
    id: "unlock",
    name: "Unlock PDF",
    description: "Remove password protection when password is known.",
    category: "Security",
    accepts: "application/pdf",
    multiple: false,
    icon: Unlock,
    options: { password: "" },
  },
  {
    id: "signature",
    name: "Digital Signature",
    description: "Attach visual signature field and metadata.",
    category: "Security",
    accepts: "application/pdf,image/png,image/jpeg",
    multiple: true,
    icon: Signature,
    options: { signer: "PDFForge", reason: "Approved" },
  },
  {
    id: "watermark",
    name: "Watermark",
    description: "Apply text or image watermarks.",
    category: "Other Tools",
    accepts: "application/pdf,image/png,image/jpeg",
    multiple: true,
    icon: Stamp,
    options: { text: "CONFIDENTIAL", opacity: 0.18, rotation: -35, position: "center" },
  },
  {
    id: "repair",
    name: "Repair PDF",
    description: "Rebuild damaged PDFs with qpdf when possible.",
    category: "Other Tools",
    accepts: "application/pdf",
    multiple: false,
    icon: WandSparkles,
    options: {},
  },
  {
    id: "ocr",
    name: "OCR PDF",
    description: "Make scanned PDFs searchable using Tesseract.",
    category: "Other Tools",
    accepts: "application/pdf,image/png,image/jpeg",
    multiple: false,
    icon: Sparkles,
    options: { language: "eng" },
  },
  {
    id: "forms",
    name: "Fillable Forms",
    description: "Inspect fields, fill values, and flatten forms.",
    category: "Other Tools",
    accepts: "application/pdf",
    multiple: false,
    icon: FormInput,
    options: { flatten: false, fields: "{}" },
  },
  {
    id: "permissions",
    name: "Permissions",
    description: "Audit PDF security status.",
    category: "Security",
    accepts: "application/pdf",
    multiple: false,
    icon: Shield,
    options: {},
  },
];

export const defaultTool = tools[0];
